###
http://localhost:8000

###
GET http://localhost:8001/api/product

###
GET http://localhost:8001/api/product/64e75a69067ed8ce809351fa

###
GET http://localhost:8001/api/postdata/


###
GET http://localhost:8001/api/user

###
GET http://localhost:8001/api/order


###
POST http://localhost:8001/api/user/login
Content-Type: application/json

{
    "email": "qw",
    "password": "qw"
}